window.SHIFTCORE_DATA = {
  sectors: [
    { id: 'elektra', name: 'Elektra' },
    { id: 'gas', name: 'Gas' },
    { id: 'water', name: 'Water' },
    { id: 'warmte', name: 'Warmte' },
    { id: 'telecom', name: 'Telecom' },
    { id: 'infra', name: 'Algemene infra' }
  ],
  certificates: [
    { id:'vca-basis', name:'VCA Basis', fullName:'Basisveiligheid VCA', category:'Veiligheid', summary:'Basiskennis over veilig en gezond werken in risicovolle omgevingen.', details:'VCA Basis is bedoeld voor uitvoerende medewerkers. Het behandelt onder meer veilig werken, persoonlijke beschermingsmiddelen, gevaarlijke stoffen, gereedschappen en noodsituaties.', validity:'Doorgaans 10 jaar', sectors:['elektra','gas','water','warmte','telecom','infra'] },
    { id:'vca-vol', name:'VCA VOL', fullName:'Veiligheid voor Operationeel Leidinggevenden', category:'Veiligheid', summary:'Veiligheidskennis voor operationeel leidinggevenden en zelfstandig werkenden.', details:'VCA VOL richt zich op medewerkers die leidinggeven of zelfstandig risico’s beoordelen. Bij zzp-inzet wordt VOL vaak gevraagd, maar de precieze eis blijft afhankelijk van de opdrachtgever.', validity:'Doorgaans 10 jaar', sectors:['elektra','gas','water','warmte','telecom','infra'] },
    { id:'gpi', name:'GPI', fullName:'Generieke Poortinstructie', category:'Toegang & veiligheid', summary:'Digitale veiligheidsinstructie voor toegang tot veel bouwplaatsen.', details:'De GPI geeft algemene veiligheidsregels voor bouwplaatsen. Afhankelijk van het project kan een specifieke variant of aanvullende poortinstructie vereist zijn.', validity:'Controleer actuele aanbiederseisen', sectors:['elektra','gas','water','warmte','telecom','infra'] },
    { id:'bei', name:'BEI', fullName:'Bedrijfsvoering Elektrische Installaties', category:'Elektra', summary:'Veiligheids- en aanwijzingsstelsel voor werkzaamheden aan elektrische infrastructuur.', details:'BEI kent verschillende domeinen, rollen en aanwijzingen. De juiste aanwijzing hangt af van het spanningsniveau, de werkzaamheden en de organisatie of netbeheerder.', validity:'Afhankelijk van opleiding, aanwijzing en werkgever', sectors:['elektra'] },
    { id:'nen3140', name:'NEN 3140', fullName:'Bedrijfsvoering van elektrische laagspanningsinstallaties', category:'Elektra', summary:'Norm voor veilig werken aan en met laagspanningsinstallaties.', details:'NEN 3140 beschrijft hoe elektrische installaties veilig worden beheerd, gebruikt en onderhouden. Rollen kunnen onder andere VOP, VP en IV omvatten.', validity:'Periodieke instructie en beoordeling vereist', sectors:['elektra','infra'] },
    { id:'viag', name:'VIAG', fullName:'Veiligheidsinstructie Aardgas', category:'Gas', summary:'Veiligheidsstelsel voor werkzaamheden aan gasvoorzieningssystemen.', details:'VIAG legt veilige werkmethoden en rollen vast voor werkzaamheden aan gasnetten. De benodigde aanwijzing verschilt per taak, drukniveau en netbeheerder.', validity:'Afhankelijk van opleiding, aanwijzing en werkgever', sectors:['gas'] },
    { id:'kiad', name:'KIAD', fullName:'Kwaliteit Instructie Aanleg Drinkwater', category:'Water', summary:'Kwaliteits- en hygiëne-eisen voor werkzaamheden aan drinkwaterleidingen.', details:'KIAD richt zich op veilige en hygiënische aanleg en werkzaamheden aan drinkwaterdistributie. De vereiste module of rol kan per opdrachtgever verschillen.', validity:'Controleer actuele regeling en opdrachtgever', sectors:['water'] },
    { id:'avp', name:'AVP', fullName:'Allround Vakman Persoonscertificering', category:'Vakbekwaamheid', summary:'Persoonscertificering voor specifieke werkzaamheden en vakbekwaamheid.', details:'De exacte betekenis en toepasbaarheid van AVP moet altijd worden gekoppeld aan de betreffende branche, opleiding en opdrachtgever. Gebruik nooit alleen de afkorting zonder context.', validity:'Afhankelijk van schema en certificerende instelling', sectors:['gas','water','warmte','infra'] },
    { id:'bhv', name:'BHV', fullName:'Bedrijfshulpverlening', category:'Veiligheid', summary:'Voor eerste hulp, brandbestrijding en ontruiming binnen een organisatie.', details:'BHV is organisatiegericht. Niet iedere medewerker hoeft BHV’er te zijn, maar op een locatie moeten voldoende opgeleide BHV’ers beschikbaar zijn.', validity:'Periodiek herhalen aanbevolen', sectors:['elektra','gas','water','warmte','telecom','infra'] },
    { id:'veilig-hijsen', name:'Veilig hijsen', fullName:'Instructie of certificering veilig hijsen en aanslaan van lasten', category:'Machines & materieel', summary:'Voor medewerkers die lasten aanslaan, begeleiden of hijswerk uitvoeren.', details:'De benodigde opleiding hangt af van het materieel, de last, de werkomgeving en de verantwoordelijkheid van de medewerker.', validity:'Afhankelijk van opleiding en werkgever', sectors:['elektra','gas','water','warmte','telecom','infra'] },
    { id:'kraan', name:'Machinistcertificaat', fullName:'Vakbekwaamheidsbewijs voor specifieke mobiele werktuigen', category:'Machines & materieel', summary:'Voor het veilig bedienen van graafmachines, kranen of andere werktuigen.', details:'De exacte eis verschilt per machine, project, hijswerk en opdrachtgever. Voor bepaalde werkzaamheden gelden aanvullende wettelijke of projectspecifieke eisen.', validity:'Afhankelijk van type certificaat', sectors:['elektra','gas','water','warmte','telecom','infra'] },
    { id:'veilig-weg', name:'Veilig werken langs de weg', fullName:'Instructie veilig werken bij of langs verkeerswegen', category:'Verkeer', summary:'Voor werkzaamheden waarbij verkeer een relevant risico vormt.', details:'De vereiste training en verkeersmaatregelen hangen af van wegbeheerder, locatie, werkzaamheden en toepasselijke richtlijnen.', validity:'Controleer opdrachtgever en wegbeheerder', sectors:['elektra','gas','water','warmte','telecom','infra'] }
  ],
  roles: [
    { id:'grondwerker', name:'Grondwerker', sectors:['gas','water','warmte','telecom','infra'], description:'Graaf-, aanvul- en ondersteunende werkzaamheden rondom kabels en leidingen.', certs:[['vca-basis','required'],['gpi','project'],['veilig-weg','project'],['veilig-hijsen','recommended']] },
    { id:'kraanmachinist', name:'Kraanmachinist', sectors:['gas','water','warmte','telecom','infra'], description:'Bedient graafmachines of ander grondverzetmaterieel op infraprojecten.', certs:[['vca-basis','required'],['kraan','required'],['gpi','project'],['veilig-hijsen','recommended']] },
    { id:'monteur-laagspanning', name:'Monteur laagspanning', sectors:['elektra'], description:'Aanleg, onderhoud en storingswerk aan laagspanningsnetten.', certs:[['vca-basis','required'],['bei','required'],['nen3140','project'],['gpi','project']] },
    { id:'eerste-monteur-laagspanning', name:'Eerste monteur laagspanning', sectors:['elektra'], description:'Zelfstandig en coördinerend werk aan laagspanningsnetten.', certs:[['vca-vol','required'],['bei','required'],['nen3140','project'],['gpi','project']] },
    { id:'voorman-elektra', name:'Voorman elektra', sectors:['elektra'], description:'Stuurt monteurs aan en bewaakt veiligheid, kwaliteit en voortgang.', certs:[['vca-vol','required'],['bei','required'],['nen3140','recommended'],['bhv','recommended']] },
    { id:'gasmonteur', name:'Gasmonteur', sectors:['gas'], description:'Aanleg, onderhoud en storingswerk aan gasleidingen en aansluitingen.', certs:[['vca-basis','required'],['viag','required'],['gpi','project'],['veilig-weg','project']] },
    { id:'eerste-gasmonteur', name:'Eerste monteur gas', sectors:['gas'], description:'Zelfstandig en coördinerend werk aan gasdistributienetten.', certs:[['vca-vol','required'],['viag','required'],['gpi','project'],['avp','project']] },
    { id:'watermonteur', name:'Monteur water', sectors:['water'], description:'Aanleg en onderhoud van drinkwaterleidingen en aansluitingen.', certs:[['vca-basis','required'],['kiad','required'],['gpi','project'],['veilig-weg','project']] },
    { id:'eerste-watermonteur', name:'Eerste monteur water', sectors:['water'], description:'Zelfstandig werk en coördinatie bij drinkwaterprojecten.', certs:[['vca-vol','required'],['kiad','required'],['gpi','project'],['avp','project']] },
    { id:'warmtemonteur', name:'Monteur warmtenetten', sectors:['warmte'], description:'Aanleg en onderhoud van leidingen en componenten voor warmte-infrastructuur.', certs:[['vca-basis','required'],['gpi','project'],['veilig-hijsen','recommended'],['avp','project']] },
    { id:'telecommonteur', name:'Telecommonteur', sectors:['telecom'], description:'Aanleg en onderhoud van koper-, coax- of glasvezelnetwerken.', certs:[['vca-basis','required'],['gpi','project'],['veilig-weg','project']] },
    { id:'uitvoerder-infra', name:'Uitvoerder infra', sectors:['elektra','gas','water','warmte','telecom','infra'], description:'Verantwoordelijk voor dagelijkse uitvoering, planning, veiligheid en kwaliteit.', certs:[['vca-vol','required'],['gpi','project'],['bhv','recommended'],['veilig-weg','recommended']] },
    { id:'werkverantwoordelijke-elektra', name:'Werkverantwoordelijke elektra', sectors:['elektra'], description:'Verantwoordelijk voor veilige bedrijfsvoering en werkorganisatie binnen het toegewezen domein.', certs:[['vca-vol','required'],['bei','required'],['nen3140','project'],['bhv','recommended']] },
    { id:'toezichthouder', name:'Toezichthouder infra', sectors:['elektra','gas','water','warmte','telecom','infra'], description:'Controleert uitvoering, veiligheid, kwaliteit en naleving van afspraken.', certs:[['vca-vol','required'],['gpi','project'],['bhv','recommended']] },
    { id:'kabelwerker', name:'Kabelwerker', sectors:['elektra','telecom'], description:'Ondersteunt bij trekken, leggen, verbinden en beschermen van kabels.', certs:[['vca-basis','required'],['gpi','project'],['veilig-weg','project']] }
  ]
};
