import Link from 'next/link';
import Explorer from '../components/Explorer';
import { certificates, roles, sectors } from '../lib/data';

export default function Home(){return <>
 <section className="hero"><div className="hero-copy"><span className="kicker">CERTIFICATENWIJZER VOOR DE INFRA</span><h1>Weet wat je nodig hebt.<br/><em>Voor je aan de slag gaat.</em></h1><p>Vind snel welke certificaten horen bij jouw functie en sector. Duidelijk uitgelegd, met aandacht voor projectspecifieke eisen.</p><div className="hero-actions"><Link className="button primary" href="#zoeken">Vind jouw certificaten</Link><Link className="button ghost" href="/certificaten">Bekijk alle certificaten</Link></div><div className="trust"><span>�o" Duidelijke status</span><span>�o" Praktische uitleg</span><span>�o" Actuele controledata</span></div></div><div className="hero-panel"><div className="panel-top"><span>VOORBEELD</span><b>Eerste monteur laagspanning</b><small>Elektra · Eerste monteur</small></div><div className="mini-list"><p><span>VCA VOL<small>Veiligheid leidinggevenden</small></span><b className="required">Verplicht</b></p><p><span>BEI LS VP<small>Aanwijzing blijft vereist</small></span><b className="required">Verplicht</b></p><p><span>GPI<small>Generieke Poortinstructie</small></span><b className="dependent">Projectafhankelijk</b></p><p><span>BHV<small>Bedrijfshulpverlening</small></span><b className="recommended">Aanbevolen</b></p></div><Link href="/functies/eerste-monteur-laagspanning">Bekijk volledig profiel �?'</Link></div></section>
 <section className="stats"><div><strong>{roles.length}</strong><span>Kernfuncties</span></div><div><strong>{certificates.length}</strong><span>Certificaten</span></div><div><strong>{sectors.length}</strong><span>Sectoren</span></div><div><strong>3</strong><span>Duidelijke statussen</span></div></section>
 <div id="zoeken"><Explorer/></div>
 <section id="sectoren" className="sectors"><span className="kicker">VERKEN PER SECTOR</span><h2>Iedere sector, eigen vereisten</h2><p>Start bij jouw vakgebied en bekijk de meest voorkomende functies en certificaten.</p><div className="sector-grid">{sectors.map(s=><Link href={`/functies?sector=${s.slug}`} key={s.slug}><i>{s.icon}</i><h3>{s.name}</h3><p>{s.description}</p><span>Bekijk sector �?'</span></Link>)}</div></section>
 <section className="notice"><div><span>i</span><div><h2>Goed om te weten</h2><p>Certificeringseisen verschillen per opdrachtgever, netbeheerder, project, aanwijzing en uit te voeren werkzaamheden. Gebruik deze wijzer als startpunt en controleer altijd de actuele projecteisen.</p></div></div><Link href="/certificaten">Lees over onze werkwijze �?'</Link></section>
 </>}

